version: '3.9'

services:
  shoveler-backend:
    container_name: shoveler-backend
    build: ./backend
    ports:
      - 8080:8080
  shoveler-frontend:
    container_name: shoveler-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
