version: '3.9'

services:
  cassandra:
    image: cassandra:4.1
  shoveler-backend:
    depends_on:
      - cassandra
    container_name: shoveler-backend
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - JWT_SIGNING_SECRET=development_secret
  shoveler-frontend:
    depends_on:
      - shoveler-backend
    container_name: shoveler-frontend
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ESLINT_NO_DEV_ERRORS=true
